name: CI - unit tests and metrics

on:
  workflow_call:
    secrets:
      shared_github_token:
        description: 'GitHub Token'
        required: true
    inputs:
      app-dir:
        type: string
        required: false
        default: "app"

jobs:
  tests_and_metrics_shared:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk # optional (jdk or jre) - defaults to jdk

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Unit Tests
        run: ./gradlew test
        env:
          GITHUB_TOKEN: ${{ secrets.shared_github_token }}

      - name: Print metrics
        run: |
          chmod +x tinkooladik/github_actions_shared/.github/transform_compose_metrics.sh ${{ inputs.app-dir }}
          echo "## Unstable arguments" >> $GITHUB_STEP_SUMMARY
          echo "The following functions were reported to have unstable arguments." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Unstable argument will make it recompose every time something changes in the parent Composable." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "$(tinkooladik/github_actions_shared/.github/transform_compose_metrics.sh)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "##" >> $GITHUB_STEP_SUMMARY
